# Generated by Django 3.1.5 on 2021-01-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0002_subcategory_threat_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threat_has_subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.subcategory')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.threat')),
            ],
        ),
        migrations.CreateModel(
            name='Threat_details_has_subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.subcategory')),
                ('threat_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.threat_details')),
            ],
        ),
        migrations.CreateModel(
            name='subcategory_has_control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.control')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.subcategory')),
            ],
        ),
    ]
