# Generated by Django 3.1.5 on 2021-01-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0003_subcategory_has_control_threat_details_has_subcategory_threat_has_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threat_details_has_subcategory',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='threat_details_has_subcategory',
            name='threat_details',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='function',
        ),
        migrations.DeleteModel(
            name='Threat_details',
        ),
        migrations.DeleteModel(
            name='Threat_details_has_subcategory',
        ),
    ]
