# Generated by Django 3.1.5 on 2021-02-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0005_auto_20210129_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='function',
        ),
    ]
