# Generated by Django 3.1.5 on 2021-02-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0006_remove_category_function'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Function',
        ),
        migrations.AddField(
            model_name='category',
            name='source',
            field=models.CharField(default='Cybersecurity framework nazionale', max_length=500),
        ),
    ]
