# Generated by Django 3.1.5 on 2021-02-10 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0012_control_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control_has_subcontrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_father', to='parsingbpmn.control')),
                ('subcontrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_child', to='parsingbpmn.control')),
            ],
        ),
    ]
