# Generated by Django 3.1.5 on 2021-02-10 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0013_control_has_subcontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control_has_relatedcontrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_relating', to='parsingbpmn.control')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_relating', to='parsingbpmn.family')),
                ('relatedcontrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_related', to='parsingbpmn.control')),
                ('relatedfamily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_related', to='parsingbpmn.family')),
            ],
        ),
    ]
