# Generated by Django 3.1.5 on 2021-02-10 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0014_control_has_relatedcontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=500)),
                ('maturity_levels', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='Contextualization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=100)),
                ('maturity_level', models.CharField(max_length=500)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.context')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.subcategory')),
            ],
        ),
    ]
