# Generated by Django 3.1.5 on 2021-02-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0015_context_contextualization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextualization',
            name='maturity_level',
            field=models.CharField(max_length=1000),
        ),
    ]
