# Generated by Django 3.1.5 on 2021-02-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0016_auto_20210210_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextualization',
            name='maturity_level',
            field=models.CharField(max_length=3000),
        ),
    ]
