# Generated by Django 3.1.5 on 2021-02-15 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0018_control_maturity_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Context',
            new_name='Context_and_profile',
        ),
        migrations.RenameModel(
            old_name='Contextualization',
            new_name='Contextualization_and_profile',
        ),
        migrations.AlterModelOptions(
            name='context_and_profile',
            options={'verbose_name': 'Context_and_profile', 'verbose_name_plural': 'Contexts_and_profiles'},
        ),
    ]
