# Generated by Django 3.1.5 on 2021-02-15 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0019_auto_20210215_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='context_and_profile',
            name='maturity_levels',
        ),
    ]
