# Generated by Django 3.1.5 on 2021-02-15 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0020_remove_context_and_profile_maturity_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='context_and_profile',
            name='type',
            field=models.CharField(default='standard', max_length=100),
        ),
        migrations.CreateModel(
            name='Profile_has_context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_level', models.CharField(max_length=100)),
                ('context_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contextualization', to='parsingbpmn.context_and_profile')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='parsingbpmn.context_and_profile')),
            ],
        ),
    ]
