# Generated by Django 3.1.5 on 2021-02-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0022_auto_20210215_1719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Context_and_profile',
            new_name='Context',
        ),
        migrations.RenameModel(
            old_name='Contextualization_and_profile',
            new_name='Contextualization',
        ),
        migrations.RenameField(
            model_name='contextualization',
            old_name='context_and_profile',
            new_name='context',
        ),
        migrations.DeleteModel(
            name='Profile_has_context',
        ),
    ]
