# Generated by Django 3.1.5 on 2021-02-19 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0023_auto_20210219_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=500)),
                ('level', models.CharField(default='minimo', max_length=100)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.AlterModelOptions(
            name='context',
            options={'verbose_name': 'Context', 'verbose_name_plural': 'Contexts'},
        ),
        migrations.RemoveField(
            model_name='context',
            name='type',
        ),
        migrations.CreateModel(
            name='profile_maturity_control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.control')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.profile')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='profile_has_subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=100)),
                ('maturity_level', models.CharField(max_length=3000)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.profile')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='context_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.context'),
        ),
        migrations.CreateModel(
            name='Fusioncontext_has_context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_child', to='parsingbpmn.context')),
                ('fusion_context_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_father', to='parsingbpmn.context')),
            ],
        ),
    ]
