# Generated by Django 3.1.5 on 2021-02-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0024_auto_20210219_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fusioncontext_has_context',
            old_name='context_id',
            new_name='context',
        ),
        migrations.RenameField(
            model_name='fusioncontext_has_context',
            old_name='fusion_context_id',
            new_name='fusion_context',
        ),
    ]
