# Generated by Django 3.1.5 on 2021-02-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0025_auto_20210219_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='context_id',
            new_name='context',
        ),
    ]
