# Generated by Django 3.1.5 on 2021-02-19 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0026_auto_20210219_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_maturity_control',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.profile'),
        ),
    ]
