# Generated by Django 3.1.5 on 2021-02-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0027_auto_20210219_1915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile_maturity_control',
        ),
    ]
