# Generated by Django 3.1.5 on 2021-02-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0029_profile_maturity_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='bpmn_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
