# Generated by Django 3.1.5 on 2021-02-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0031_remove_context_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='method',
        ),
    ]
