# Generated by Django 3.1.5 on 2021-03-04 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0034_remove_contextualization_maturity_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_has_subcategory',
            name='maturity_level',
        ),
    ]
