# Generated by Django 3.1.5 on 2021-03-04 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0036_profile_has_subcategory_maturity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='maturity_level',
            name='context',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.context'),
        ),
    ]
