# Generated by Django 3.1.5 on 2021-03-05 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0038_auto_20210305_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control_framework',
            name='description',
        ),
    ]
