# Generated by Django 3.1.5 on 2021-03-08 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0040_auto_20210305_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threat_has_family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.family')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.threat')),
            ],
        ),
    ]
