# Generated by Django 3.1.5 on 2021-03-10 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0042_profile_maturity_control_implementation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='framework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.control_framework'),
        ),
    ]
