# Generated by Django 3.1.5 on 2021-03-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0043_profile_framework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
