# Generated by Django 3.1.5 on 2021-03-29 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsingbpmn', '0044_auto_20210310_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='family',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='parsingbpmn.family'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
